name: cg_net_mobile
description: CG-NET — customer-facing ISP mobile app
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^14.6.2
  easy_localization: ^3.0.7
  dio: ^5.7.0
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.3
  lottie: ^3.1.3
  shimmer: ^3.0.0
  connectivity_plus: ^6.1.0
  package_info_plus: ^8.1.1
  intl: ^0.20.2
  flutter_lucide: ^1.42.0
  google_fonts: ^8.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/mock/
    - assets/translations/
    - assets/lottie/
    - assets/images/
    - assets/images/packages/
    - assets/images/banners/
    - assets/images/services/
